# Generated by Django 2.0.4 on 2018-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dytt8',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
