# Generated by Django 2.0.4 on 2018-04-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dytt8',
            options={'managed': False},
        ),
    ]
