# Generated by Django 2.0.4 on 2018-04-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180415_2035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dytt8',
            table='dytt8',
        ),
    ]
